NAME := ircserv

SRCS := src/main.cpp src/IRCServer.cpp src/Client.cpp src/Channel.cpp\
		src/RequestHandler.cpp src/IRCMessage.cpp src/Socket.cpp \
		src/IRCParser.cpp src/Utils.cpp src/IOWrapper.cpp src/IRCLogger.cpp \
		src/IRCSignal.cpp \
		src/commands/ACommand.cpp src/commands/CommandCap.cpp \
		src/commands/CommandNick.cpp src/commands/CommandPass.cpp \
		src/commands/CommandUser.cpp src/commands/CommandPing.cpp \
		src/commands/CommandJoin.cpp src/commands/CommandTopic.cpp \
		src/commands/CommandMode.cpp src/commands/CommandPrivMsg.cpp \
		src/commands/CommandBroadCast.cpp

OBJS := $(SRCS:.cpp=.o)
CXXFLAGS += -I./include -I./include/commands -Wall -Wextra -Werror -O0 -g -std=c++98 -pedantic-errors -DDEBUG
ifdef PROD_FLG
CXXFLAGS := -I./include -I./include/commands -Wall -Wextra -Werror -O2 -std=c++98 -pedantic-errors
endif
CXX := c++

.PHONY: all
all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(OBJS) -o $(NAME)

.PHONY: clean
clean:
	$(RM) $(OBJS)

.PHONY: fclean
fclean: clean
	$(RM) $(NAME)

.PHONY: re
re: fclean all


